using DbManager.Parser;
using System;
using System.Runtime.CompilerServices;


namespace DbManager
{
    public class ColumnDefinition
    {
        public enum DataType { String, Int, Double }

        public DataType Type;
        public string Name { get; private set; }


        public ColumnDefinition(DataType type, string name)
        {
            //TODO DEADLINE 1.A: Initialize member variables
            this.Type = type;
            this.Name = name;

        }

        private const string Delimiter = "->";
        private const string DelimiterEncoded = "[ARROW]";

        private static string Encode(string value)
        {
            //TODO DEADLINE 1.C: Encode the delimiter in the value
            return value.Replace(Delimiter, DelimiterEncoded);

        }

        private static string Decode(string value)
        {
            //TODO DEADLINE 1.C: Decode the delimiter in the value
            return value.Replace(DelimiterEncoded, Delimiter);

        }

        public string AsText()
        {
            //TODO DEADLINE 1.C: Return the column as a string with the name and the type separated by the delimiter
            string result;
            return result = Encode(Name) + Delimiter + Type.ToString();

        }

        public static ColumnDefinition Parse(string value)
        {
            //TODO DEADLINE 1.C: Parse the column's name and type from a string generated by AsText()
            ColumnDefinition cd;
            string[] parts = value.Split(Delimiter);
            string parsedValue = Decode(parts[0]);
            DataType type;
            switch (parts[1])
            {
                case "String":
                    type = DataType.String;
                    break;
                case "Int":
                    type = DataType.Int;
                    break;
                case "Double":
                    type = DataType.Double;
                    break;
                default:
                    type = DataType.String;
                    break;
            }
            cd = new ColumnDefinition(type, parsedValue);
            return cd;
        }
    }
}
